//Generated by GuiGenie - Copyright (c) 2004 Mario Awad.
//Home Page http://guigenie.cjb.net - Check often for new versions!

import java.awt.*;
import java.awt.event.*;
import java.util.List;
import java.util.ArrayList;

import javax.swing.*;
import javax.swing.event.*;

public class AddPersonScreen extends JPanel {
    private JRadioButton empBut;
    private JRadioButton cusBut;
    private JLabel jcomp3;
    private JLabel jcomp4;
    private JLabel jcomp5;
    private JTextField jcomp6;
    private JTextField jcomp7;
    private JTextField jcomp8;
    private JTextField jcomp9;
    private JLabel jcomp10;
    private JTextField jcomp11;
    private JLabel jcomp12;
    
    private JButton addPerson;
    
    private DefaultListModel empLM;
    private DefaultListModel cusLM;

    public AddPersonScreen(DefaultListModel empLM, DefaultListModel cusLM) {
        //construct components
        empBut = new JRadioButton ("Employee");
        cusBut = new JRadioButton ("Customer");
        jcomp3 = new JLabel ("ID");
        jcomp4 = new JLabel ("Name");
        jcomp5 = new JLabel ("Number");
        jcomp6 = new JTextField (5);
        jcomp7 = new JTextField (5);
        jcomp8 = new JTextField (5);
        jcomp9 = new JTextField (5);
        jcomp10 = new JLabel ("Email");
        jcomp11 = new JTextField (5);
        jcomp12 = new JLabel ("Salary");
        addPerson = new JButton ("Add Person");

        ButtonGroup buttonG = new ButtonGroup();
        buttonG.add(empBut);
        buttonG.add(cusBut);
        
        empBut.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
            	jcomp11.setEnabled(true);
            	jcomp12.setEnabled(true);
            }
        });
        
        cusBut.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
            	jcomp11.setEnabled(false);
            	jcomp12.setEnabled(false);
            }
        });
        
        addPerson.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
            	List<JTextField> list = new ArrayList<JTextField>();
            	list.add(jcomp6);
            	list.add(jcomp7);
            	list.add(jcomp8);
            	list.add(jcomp9);
            	
            	boolean cont = true;
            	for(JTextField tf : list)	{
            		if (tf.getText().equals(""))
            			cont = false;
            	}
            	if(!cont)	{}
            	else	{
	            	
	            	if (empBut.isEnabled())	{
	            		list.add(jcomp11);
	            		for(JTextField tf : list)	{
	                		if (tf.getText().equals(""))
	                			cont = false;
	                	}
	            		if(!cont)	{}
	            		else	{
	            			addEmployeeToDB(list);
	            		}
	            	}
	        
	            	if (cusBut.isEnabled())	{
	            		addCustomerToDB(list);
	            	}
            	}
            }
        });
        
        //adjust size and set layout
        setPreferredSize (new Dimension (944, 563));
        setLayout (null);

        //add components
        add (empBut);
        add (cusBut);
        add (jcomp3);
        add (jcomp4);
        add (jcomp5);
        add (jcomp6);
        add (jcomp7);
        add (jcomp8);
        add (jcomp9);
        add (jcomp10);
        add (jcomp11);
        add (jcomp12);
        add (addPerson);

        //set component bounds (only needed by Absolute Positioning)
        empBut.setBounds (10, 10, 100, 25);
        cusBut.setBounds (10, 35, 100, 25);
        jcomp3.setBounds (150, 5, 100, 25);
        jcomp4.setBounds (280, 5, 100, 25);
        jcomp5.setBounds (410, 5, 100, 25);
        jcomp6.setBounds (565, 30, 130, 25);
        jcomp7.setBounds (150, 30, 100, 25);
        jcomp8.setBounds (280, 30, 100, 25);
        jcomp9.setBounds (410, 30, 120, 25);
        jcomp10.setBounds (565, 5, 100, 25);
        jcomp11.setBounds (725, 30, 130, 25);
        jcomp12.setBounds (725, 5, 100, 25);
        addPerson.setBounds(10, 70, 100, 25);
    }

    private void addEmployeeToDB(List<JTextField> list)	{
    	SQLConnection sqlCon = new SQLConnection();
    	sqlCon.openConnection();
    	
    	
    	sqlCon.closeConnection();
    }
    
    private void addCustomerToDB(List<JTextField> list)	{
    	SQLConnection sqlCon = new SQLConnection();
    	sqlCon.openConnection();
    	
    	
    	sqlCon.closeConnection();
    }

	public static void main (String[] args) {
        JFrame frame = new JFrame ("AddPersonScreen");
        frame.setDefaultCloseOperation (JFrame.EXIT_ON_CLOSE);
        frame.getContentPane().add (new AddPersonScreen(null, null));
        frame.pack();
        frame.setVisible (true);
    }
}
