//Generated by GuiGenie - Copyright (c) 2004 Mario Awad.
//Home Page http://guigenie.cjb.net - Check often for new versions!

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import javax.swing.event.*;

public class MainScreen extends JPanel {
    private JButton peopleBut;
    private JButton inventBut;
    private JButton transBut;
    
    private static JFrame frame;

    public MainScreen(JFrame frameM) {
        frame = frameM;
    	//construct components
        peopleBut = new JButton ("People");
        inventBut = new JButton ("Inventory");
        transBut = new JButton ("Transactions");

        //adjust size and set layout
        setPreferredSize (new Dimension (944, 563));
        setLayout (null);

        //add components
        add (peopleBut);
        add (inventBut);
        add (transBut);

        //set component bounds (only needed by Absolute Positioning)
        peopleBut.setBounds (20, 20, 100, 20);
        inventBut.setBounds (155, 20, 100, 20);
        transBut.setBounds (290, 20, 120, 20);
        
        peopleBut.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
            	frame.dispose();
            	JFrame frame = new JFrame ("PeopleScreen");
                frame.getContentPane().add (new PeopleScreen(frame));
                frame.pack();
                frame.setVisible (true);
            }
        });
        
        inventBut.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
            	frame.dispose();
            	JFrame frame = new JFrame ("InventoryScreen");
                frame.getContentPane().add (new InventoryScreen(frame));
                frame.pack();
                frame.setVisible (true);
            }
        });
        
        transBut.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
            	frame.dispose();
            	JFrame frame = new JFrame ("TransactionScreen");
                frame.getContentPane().add (new TransactionScreen(frame));
                frame.pack();
                frame.setVisible (true);
            }
        });
    }

    public static void main (String[] args) {
        frame = new JFrame ("MainScreen");
        frame.setDefaultCloseOperation (JFrame.EXIT_ON_CLOSE);
        frame.getContentPane().add (new MainScreen(frame));
        frame.pack();
        frame.setVisible (true);
    }
}
