//Generated by GuiGenie - Copyright (c) 2004 Mario Awad.
//Home Page http://guigenie.cjb.net - Check often for new versions!

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import javax.swing.event.*;

public class MainScreen extends JPanel {
    private JButton jcomp1;
    private JButton jcomp2;
    private JButton jcomp3;
    
    private static JFrame frame;

    public MainScreen() {
        //construct components
        jcomp1 = new JButton ("People");
        jcomp2 = new JButton ("Inventory");
        jcomp3 = new JButton ("Transactions");

        //adjust size and set layout
        setPreferredSize (new Dimension (944, 563));
        setLayout (null);

        //add components
        add (jcomp1);
        add (jcomp2);
        add (jcomp3);

        //set component bounds (only needed by Absolute Positioning)
        jcomp1.setBounds (20, 20, 100, 20);
        jcomp2.setBounds (155, 20, 100, 20);
        jcomp3.setBounds (295, 20, 140, 25);
        
        jcomp1.addActionListener(new ActionListener() {

            public void actionPerformed(ActionEvent e) {
            	frame.dispose();
            	JFrame frame = new JFrame ("PeopleScreen");
                frame.getContentPane().add (new PeopleScreen());
                frame.pack();
                frame.setVisible (true);
            }
        });
    }

    public static void main (String[] args) {
        frame = new JFrame ("MainScreen");
        frame.setDefaultCloseOperation (JFrame.EXIT_ON_CLOSE);
        frame.getContentPane().add (new MainScreen());
        frame.pack();
        frame.setVisible (true);
    }
}
